apiVersion: v1
kind: ConfigMap
metadata:
  name: cmap-gym-investire-iscritto-ms
data:
  application.properties: |
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://10.43.107.205:5432/dipendenti 
    spring.datasource.username=dba_user
    spring.datasource.password=Neotech01!
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
