apiVersion: v1
kind: ConfigMap
metadata:
  name: cmap-gym-investire-iscritto-ms
  namespace: ns-gym-investire-coll
data:
  application.properties: |
    server.port=8080
    banner.location=classpath:banner.txt
    logging.level.root=info
    management.endpoints.web.exposure.include=health
    management.endpoint.health.show-details=always
    spring.security.user.name=actuator
    spring.security.user.password=actuator
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://16.16.192.79:5432/gym_investire 
    spring.datasource.username=dba_user
    spring.datasource.password=Neotech01!
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
    app.security.enabled=false
    app.jwt.secret=my-secret-key