apiVersion: v1
kind: ConfigMap
metadata:
  name: cmap-gym-investire-iscritto-ms
data:
  application.properties: |
    server.port=8080
    banner.location=classpath:banner.txt
    logging.level.root=debug
    management.endpoints.web.exposure.include=health
    management.endpoint.health.show-details=always
    spring.security.user.name=actuator
    spring.security.user.password=actuator
